//PROGRAM TO STUDY FUNCTIONING OF INPUT-OUTPUT AND WAIT LOOP
.ORIG X10
.START X10

MOV b X5 R1	//STORING A NUMBER IN R1

//THIS IS THE WAIT/INFINITE LOOP 
LOOP: IN X0 R2		//TAKE INPUT FROM PORT 0 AND STORE IT IN R2
	COMP b R1 R2	//COMPARE TO SEE IF INPUT VALUE IS EQUAL TO NUMBER STORED IN R1
	JNE LOOP

HALT