//PROGRAM TO FIND AVERAGE OF 6 NUMBERS

.ORIG x10
.START x10

//MOVING NUMBERS IN REGISTERS FOR STORING IN MAIN MEMORY
MOV B x3 R1
MOV B x1 R2
MOV B x2 R3
MOV B x3 R4
MOV B x4 R5
MOV B x5 R6

//STORING NUMBERS IN MEMORY, x100 TO x105
STORE B [X100] R1
STORE B [X101] R2
STORE B [X102] R3
STORE B [X103] R4
STORE B [X104] R5
STORE B [X105] R6

//TO FIND AVERAGE, WE FIND SUM OF NUMBERS

MOV W X100 R7	//R7 STORES MEMORY LOCATIONS, SINCE WE NEED TO RETRIEVE THE NUMBERS FROM MEMORY
MOV W x0 R8	//R8 STORES THE SUM

SUM: LOAD B [R7] R15	//LOADING THE NUMBER STORED AT A PARTICULAR MEMORY LOCATION IN R7
	ADD B R15 R8	//ADDING THE LOADED NUMBER TO THE SUM IN R8
	ADD W x1 R7	//INCREMENTING THE MEMORY LOCATION TO POINT TO LOCATION OF NEXT STORED NUMBER
	COMP W x105 R7	//SINCE THE LAST NUMBER IS IN x105 WE CHECK IF VALUE OF R7 HAS REACHED x105
	JGE SUM		//IF x105 < R7 ALL THE NUMBERS HAVE BEEN ADDED TO THE SUM AND HENCE NO NEED TO LOOP FURTHER, ELSE LOOP

//SUM OF NUMBERS IS IN R8

MOV B x6 R9 	//TOTAL 6 NUMBERS

//NOW WE MUST DIVIDE SUM BY TOTAL NUMBERS TO GET AVERAGE
MOV W R8 R10	//WE COPY THE SUM IN R10. THIS IS THE DIVIDEND FOR DIVISION OPERATION
MOV W x0 R11	//R11 CONTAINS QUOTIENT IN CEILING FORM WHICH IS THE CEILING OF AVERAGE OF NUMBERS

DIVISION: SUB B R9 R10		//DIVISION MEANS CONTINUOUS SUBTRACTION. AT LEAST ONE DIVISION IS DONE SINCE WE HAVE TO GIVE CEILING OF AVERAGE
		ADD B x1 R11	/ADD 1 TO QUOTIENT
		COMP B x0 R10	//COMPARE TO SEE IF FURTHER DIVISION IS POSSIOBLE
		JLT DIVISION	//IF DIVIDEND IN R10 > 0 THEN DIVIDE AGAIN SINCE WE WANT CEILING OF AVERAGE, WE GO ON DIVIDING TILL DIVIDEND IN R10 > 0

STORE B [x107] R11	//STORING THE RESULT AT LOCATION x107

.END