
import java.awt.*;
import java.net.*;
import java.awt.event.*;
import javax.swing.*;
import java.io.*;
import java.awt.print.*;
import java.util.*;
import javax.swing.undo.*;
import javax.swing.filechooser.FileFilter;

/**
* Handles the menu actions of Execution menu in the application
*/

public class HelpMenuAction extends AbstractAction {
    protected LC frame;

    public HelpMenuAction(String name, Icon icon, String descrip,
    Integer mnemonic, KeyStroke accel, LC gui) {
        super(name, icon);
        putValue(SHORT_DESCRIPTION, descrip);
        putValue(MNEMONIC_KEY, mnemonic);
        putValue(ACCELERATOR_KEY, accel);
        frame = gui;
    }

    /**
    * implements the actionPerformed method of AbstractAction
    * triggered when an event is generated by any component
    *
    * @param e component triggering this call
    */
    public void actionPerformed(ActionEvent e) {
        if(e.getActionCommand().equals("Help"))
        helpHelpAction(e);
        if(e.getActionCommand().equals("Arch"))
        helpArchAction(e);
        if(e.getActionCommand().equals("About"))
        helpAboutAction(e);
    }


    /**
    * Open help window.
    *
    * @param e component triggering this call
    */
    public void helpHelpAction(ActionEvent e) {
        URL index = ClassLoader.getSystemResource("NICE-help.rtf");
        new HelpWindow("Welcome to NICE help ....", index);
    }

    /**
    * Open window to show processor architecture.
    *
    * @param e component triggering this call
    */
    public void helpArchAction(ActionEvent e) {
        URL index = ClassLoader.getSystemResource("Assembler.rtf");
        new HelpWindow("NICE Assembler help", index);
    }

    /**
    * Open window for 'About the program'.
    *
    * @param e component triggering this call
    */
    public void helpAboutAction(ActionEvent e) {
        JFrame jf = new JFrame();
        JOptionPane.showMessageDialog(jf,"NICE Assembler & Simulator (Version 1.0).\n\n"+
        "Copyright 2008.\n"+
        "Naresh Jotwani, Pradeep Singh & Yogesh Bansal.\n\n"+
        "Toolbar and menu icons are from:\n"+
        " --> tango.freedesktop.org,\n"+
        " --> www.kde-look.org,\n"+
        " --> www.icon-king.com\n\n", 
        "About this program:", 
        JOptionPane.INFORMATION_MESSAGE
        );
    }
}